### ISSUE TITLE
maintenance reboot!

### ISSUE THREAD

**Issue by balint-backmaker** [testcontainers/testcontainers-python#405]
# maintenance reboot

Hey folks!
As you all know, this project has seen better days, as evidenced by:
- the numerous issues/pull-requests that do not have any answers or progress in a long time
- as well as not having any releases to `pypi` done in the entirety of 2023 :cry: 

I know many people are using `testcontainers` in Python so we want to make it right for you!

To not beat around the bush, here is a short-list of what we'll fix ASAP, but each will be explained further below (or in detailed issues):
- [x] Automate the release process via `release-please` - see #429 
- [x] Ease dependency management and packaging: move to `pyproject.toml`, possibly via `poetry` (already surfaced in #204)

Follow-up changes:
- [x] Re-instate the `compose` module with compose v2 - previous version was removed in a recent commit to `main` and is now defunct (breaking change, because the compose v1 python lib is defunct, too much risk otherwise!)
- [x] Release `4.0.0` - there are too many changes to comb through manually if they are breaking or not and compose is definitely a breaking change
```[tasklist]
### Tasks
- [ ] https://github.com/testcontainers/testcontainers-python/issues/204
- [ ] https://github.com/testcontainers/testcontainers-python/issues/358
- [ ] https://github.com/testcontainers/testcontainers-python/pull/429
```

**Comment by alexanderankin** [comment]
@SergeyPirogov and @tillahoffmann can one of you add me as owner on https://pypi.org/project/testcontainers/ ? I'm https://pypi.org/user/daveankin/ (`daveankin`) on there - in service of figuring out automated releases. Otherwise we'd have to look into PEP 541.

**Comment by totallyzen** [comment]
for keen eyes:
- I have removed #305 as proper completion of this is harder than expected, we _need_ to prove the `4.0.0` release - not dropping the overall thing, just detaching from the "ready to release" criteria. More strong typing coming in with future `4.X` releases
- I have removed "triage every issue" as it's more an ongoing task than a reboot marker

**Comment by totallyzen** [comment]
Hey folks! We now have a complete release process and `compose` is back in action. 
I'm closing this issue and open two new issues to follow-up
- `4.x: quality of life`, examples would be: typed packages, new modules, etc
- `5.x: API improvements`, examples would be: introducing Ryuk (to be up to date with other TC implementations) and improve container guarantees
